### Project specific config ###
os: linux
language: node_js
node_js: "lts/*"

jobs:
  include:
    # Run the package specs
    - stage: test
      env: ATOM_CHANNEL=stable
    - stage: test
      env: ATOM_CHANNEL=beta

    # Check the commit messages
    - stage: test
      language: node_js
      node_js: lts/*
      install:
        - npm install
      script:
        - commitlint-travis

    - stage: release
      # Since the deploy needs APM, currently the simplest method is to run
      # build-package.sh.
      before_script:
        - export PATH=${PATH}:${HOME}/atom/usr/bin/
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release

### Generic setup follows ###
install:
  - curl -s -O https://raw.githubusercontent.com/atom/ci/master/build-package.sh
  - chmod u+x build-package.sh
  - "./build-package.sh"

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - master
    - "/^greenkeeper/.*$/"

git:
  depth: 10

sudo: false

dist: trusty

addons:
  apt:
    packages:
    - build-essential
    - fakeroot
    - git
    - libsecret-1-dev

stages:
  - test
  - name: release
    if: (NOT type = pull_request) AND branch = master
